# Generated by Django 3.2 on 2023-02-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_number',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
